### ISSUE TITLE
Investigate CMake support

### ISSUE THREAD

**Issue by eXpl0it3r** [eXpl0it3r/SFML-dependencies#1]
Looks like some libraries have added CMake support, which should be it easier to build them.

**Comment by miketweaver** [comment]
Ogg CMake: https://github.com/xiph/ogg#building-with-cmake
Vorbis CMake: https://github.com/xiph/vorbis#building-with-cmake
libjpeg-turbo CMake: https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/CMakeLists.txt
OpenAL CMake: https://github.com/kcat/openal-soft#source-install

**Comment by eXpl0it3r** [comment]
CMake has been added with #2
